//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceForInsert
{
    using System;
    using System.Collections.Generic;
    
    public partial class luongnhanvien
    {
        public string nhanvienma { get; set; }
        public string luongcobanma { get; set; }
        public string phucapma { get; set; }
        public string ma { get; set; }
    
        public virtual luongcoban luongcoban { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        public virtual phucap phucap { get; set; }
    }
}
