//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceForInsert
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvienhocvan
    {
        public string nhanvienma { get; set; }
        public string hocvanma { get; set; }
        public string ma { get; set; }
        public Nullable<System.DateTime> thoigiantotnghiep { get; set; }
        public string tentruong { get; set; }
        public string chuyennganh { get; set; }
    
        public virtual hocvan hocvan { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
