//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceForInsert
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinkhacvenhanvien
    {
        public string giadinh { get; set; }
        public string taikhoannganhang { get; set; }
        public string manganhang { get; set; }
        public string nhanvienma { get; set; }
        public Nullable<int> soLD { get; set; }
        public Nullable<int> soBHXH { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
